[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Books"
  pageRef = "books"
  weight = 30


[[main]]
  name = "Newsletter"
  pageRef = "newsletter"
  weight = 50
